[tool.poetry]
name = "inventory"
version = "0.1.0"
description = ""
authors = ["Johannes Schriewer <hallo@dunkelstern.de>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1"
gunicorn = "^20.0.4"
whitenoise = "^5.0.1"
commentjson = "^0.8.3"
psycopg2 = "^2.8"
django-nested-admin = "^3.3.2"
pillow = "^8.0"

[tool.poetry.dev-dependencies]
mypy = "*"
flake8 = "^3.7"
pylint = "^2.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
