# Generated by Django 3.0.4 on 2020-08-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AddField(
            model_name='distributor',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_related', to='inventory.Container'),
        ),
        migrations.AlterField(
            model_name='box',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_related', to='inventory.Container'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='search_link',
            field=models.URLField(blank=True, help_text='Use {} for search placeholder', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_related', to='inventory.Container'),
        ),
    ]
