# Generated by Django 3.1.4 on 2020-12-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_base_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
