# Generated by Django 3.0.4 on 2020-08-03 22:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200803_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='documentation',
        ),
        migrations.AlterField(
            model_name='item',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Custom metadata, used by templates'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
    ]
