# Generated by Django 3.0.4 on 2020-08-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200804_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
