# Generated by Django 5.1.4 on 2025-01-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tag_options_alter_area_container_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='formfactor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='layout',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ('name',)},
        ),
    ]
