# Generated by Django 3.1.4 on 2020-12-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='show_sub_area',
            field=models.BooleanField(default=True, help_text='Allow sub-areas to be defined in this area'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='show_boxes',
            field=models.BooleanField(default=True, help_text='Allow boxes to be defined directly in this workshop'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.PositiveIntegerField(default=1, help_text='Number of sub-compartments this item takes up'),
        ),
    ]
