# Generated by Django 5.1.4 on 2025-01-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_default_ordering'),
    ]

    operations = [
        migrations.RunSQL("CREATE COLLATION IF NOT EXISTS numeric (provider = icu, locale = 'en@colNumeric=yes');"),
        migrations.AlterField(
            model_name='formfactor',
            name='description',
            field=models.CharField(db_collation='numeric', max_length=4096),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='name',
            field=models.CharField(db_collation='numeric', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(db_collation='numeric', max_length=4096),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(db_collation='numeric', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(db_collation='numeric', max_length=4096),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_collation='numeric', max_length=255, unique=True),
        ),
    ]
