# Generated by Django 3.0.4 on 2020-08-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200804_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
