# Generated by Django 5.1.4 on 2025-01-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_sorting_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Number of parts available'),
        ),
        migrations.AddField(
            model_name='item',
            name='low_count',
            field=models.PositiveIntegerField(default=0, help_text='Low watermark on which to alert ordering more'),
        ),
    ]
