# Generated by Django 5.1.4 on 2025-01-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_count_item_low_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='track_amount',
            field=models.BooleanField(default=False, help_text='Show item count in overview and warn on low watermarks'),
        ),
    ]
