# Generated by Django 3.0.4 on 2020-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_documentation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='documentation',
            field=models.ManyToManyField(to='inventory.Documentation'),
        ),
    ]
