# Generated by Django 5.1.4 on 2025-01-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_settings_track_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='currency',
            field=models.CharField(default='Euro', help_text='Currency name', max_length=30),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency_symbol',
            field=models.CharField(default='&euro;', help_text='Currency symbol', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='currency_symbol_position',
            field=models.BooleanField(default=True, help_text='Currency symbol after amount'),
        ),
    ]
